chore: update branch protection

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,11 @@
+#!/bin/sh
+
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "main" ] || [ "$branch" = "test" ]; then
+  echo "You can't commit directly to $branch branch"
+  echo "Please create a feature branch and make a pull request"
+  exit 1
+fi
+
 npm run test:run
